version: '3'
services:
  movies:
    image: gurajalasravani/moviespaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: gurajalasravani/trainpaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: gurajalasravani/dthpaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: gurajalasravani/reachargepaytm:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

